spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-sender-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ru.mkenopsia.tasktrackeremailsender.dto